//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "GameMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Game.Direction", ScriptName="EGrpcGameDirection"))
enum class EGrpcGameDirection : uint8
{
    UNKNOWN=0,
    NORTH=1,
    SOUTH=2,
    EAST=3,
    WEST=4,
    UP=5,
    DOWN=6,
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.GetDungeonDataRequest"))
struct FGrpcGameGetDungeonDataRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PlayerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.GetDungeonDataResponse",
    HasNativeMake = "TurboLinkGrpc.GrpcGameGetDungeonDataResponseHelperLibrary.MakeGetDungeonDataResponse",
    HasNativeBreak = "TurboLinkGrpc.GrpcGameGetDungeonDataResponseHelperLibrary.BreakGetDungeonDataResponse"))
struct FGrpcGameGetDungeonDataResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    TArray<TSharedPtr<FGrpcGameRoomResponse>> Rooms;
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.LoginRequest"))
struct FGrpcGameLoginRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Username = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.LoginResponse"))
struct FGrpcGameLoginResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PlayerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.LogoutRequest"))
struct FGrpcGameLogoutRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PlayerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.LogoutResponse"))
struct FGrpcGameLogoutResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PlayerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.PlayerRequest"))
struct FGrpcGamePlayerRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PlayerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.MoveRequest"))
struct FGrpcGameMoveRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PlayerId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcGameDirection Direction = static_cast<EGrpcGameDirection>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.RoomResponse"))
struct FGrpcGameRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 X = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 Y = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 Z = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Discovered = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Data = false;
};

UCLASS()
class UGrpcGameGetDungeonDataResponseHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Game", meta=(BlueprintThreadSafe))
    static FGrpcGameGetDungeonDataResponse MakeGetDungeonDataResponse( 
        TArray<FGrpcGameRoomResponse> Rooms 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Game", meta=(BlueprintThreadSafe))
    static void BreakGetDungeonDataResponse(const FGrpcGameGetDungeonDataResponse& GetDungeonDataResponse,  
        TArray<FGrpcGameRoomResponse>& Rooms 
    );
};
