//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SGame/GameMessage.h"
#include "GameClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDungeonServiceLoginResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGameLoginResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDungeonServiceLogoutResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGameLogoutResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDungeonServiceGetCurrentRoomResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGameRoomResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDungeonServiceMoveResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGameRoomResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDungeonServiceGetDungeonDataResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGameGetDungeonDataResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UDungeonServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnDungeonServiceLoginResponse OnLoginResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDungeonServiceLogoutResponse OnLogoutResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDungeonServiceGetCurrentRoomResponse OnGetCurrentRoomResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDungeonServiceMoveResponse OnMoveResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDungeonServiceGetDungeonDataResponse OnGetDungeonDataResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitLogin();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void Login(FGrpcContextHandle Handle, const FGrpcGameLoginRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitLogout();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void Logout(FGrpcContextHandle Handle, const FGrpcGameLogoutRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetCurrentRoom();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GetCurrentRoom(FGrpcContextHandle Handle, const FGrpcGamePlayerRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitMove();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void Move(FGrpcContextHandle Handle, const FGrpcGameMoveRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetDungeonData();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GetDungeonData(FGrpcContextHandle Handle, const FGrpcGameGetDungeonDataRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

