//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "GameMessage.h"
#include "GameNode.generated.h"

class UDungeonService;
class UDungeonServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallDungeonServiceLogin : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FDungeonServiceLoginDelegate, const FGrpcResult&, GrpcResult, const FGrpcGameLoginResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|DungeonService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call DungeonService Login",
		AdvancedDisplay = 2))
	static UCallDungeonServiceLogin* Login(UObject* WorldContextObject, const FGrpcGameLoginRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceLoginDelegate OnLoginResponse;

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceLoginDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UDungeonService* DungeonService;
	
	UPROPERTY()
	UDungeonServiceClient* DungeonServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGameLoginRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameLoginResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallDungeonServiceLogout : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FDungeonServiceLogoutDelegate, const FGrpcResult&, GrpcResult, const FGrpcGameLogoutResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|DungeonService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call DungeonService Logout",
		AdvancedDisplay = 2))
	static UCallDungeonServiceLogout* Logout(UObject* WorldContextObject, const FGrpcGameLogoutRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceLogoutDelegate OnLogoutResponse;

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceLogoutDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UDungeonService* DungeonService;
	
	UPROPERTY()
	UDungeonServiceClient* DungeonServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGameLogoutRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameLogoutResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallDungeonServiceGetCurrentRoom : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FDungeonServiceGetCurrentRoomDelegate, const FGrpcResult&, GrpcResult, const FGrpcGameRoomResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|DungeonService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call DungeonService GetCurrentRoom",
		AdvancedDisplay = 2))
	static UCallDungeonServiceGetCurrentRoom* GetCurrentRoom(UObject* WorldContextObject, const FGrpcGamePlayerRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceGetCurrentRoomDelegate OnGetCurrentRoomResponse;

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceGetCurrentRoomDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UDungeonService* DungeonService;
	
	UPROPERTY()
	UDungeonServiceClient* DungeonServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGamePlayerRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameRoomResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallDungeonServiceMove : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FDungeonServiceMoveDelegate, const FGrpcResult&, GrpcResult, const FGrpcGameRoomResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|DungeonService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call DungeonService Move",
		AdvancedDisplay = 2))
	static UCallDungeonServiceMove* Move(UObject* WorldContextObject, const FGrpcGameMoveRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceMoveDelegate OnMoveResponse;

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceMoveDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UDungeonService* DungeonService;
	
	UPROPERTY()
	UDungeonServiceClient* DungeonServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGameMoveRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameRoomResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallDungeonServiceGetDungeonData : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FDungeonServiceGetDungeonDataDelegate, const FGrpcResult&, GrpcResult, const FGrpcGameGetDungeonDataResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|DungeonService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call DungeonService GetDungeonData",
		AdvancedDisplay = 2))
	static UCallDungeonServiceGetDungeonData* GetDungeonData(UObject* WorldContextObject, const FGrpcGameGetDungeonDataRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceGetDungeonDataDelegate OnGetDungeonDataResponse;

	UPROPERTY(BlueprintAssignable)
	FDungeonServiceGetDungeonDataDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UDungeonService* DungeonService;
	
	UPROPERTY()
	UDungeonServiceClient* DungeonServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGameGetDungeonDataRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameGetDungeonDataResponse& Response);

	void Shutdown();
};
