//Generated by TurboLink CodeGenerator, do not edit!
#include "SGame/GameMessage.h"
#include "SGame/GameMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcGameGetDungeonDataRequest, ::game::GetDungeonDataRequest)
DEFINE_JSON_FUNCTIONS(FGrpcGameGetDungeonDataResponse, ::game::GetDungeonDataResponse)
DEFINE_JSON_FUNCTIONS(FGrpcGameLoginRequest, ::game::LoginRequest)
DEFINE_JSON_FUNCTIONS(FGrpcGameLoginResponse, ::game::LoginResponse)
DEFINE_JSON_FUNCTIONS(FGrpcGameLogoutRequest, ::game::LogoutRequest)
DEFINE_JSON_FUNCTIONS(FGrpcGameLogoutResponse, ::game::LogoutResponse)
DEFINE_JSON_FUNCTIONS(FGrpcGamePlayerRequest, ::game::PlayerRequest)
DEFINE_JSON_FUNCTIONS(FGrpcGameMoveRequest, ::game::MoveRequest)
DEFINE_JSON_FUNCTIONS(FGrpcGameRoomResponse, ::game::RoomResponse)

FGrpcGameGetDungeonDataResponse UGrpcGameGetDungeonDataResponseHelperLibrary::MakeGetDungeonDataResponse( 
    TArray<FGrpcGameRoomResponse> Rooms 
)
{
    FGrpcGameGetDungeonDataResponse GetDungeonDataResponse;
    for (const auto& element : Rooms)
    {
        GetDungeonDataResponse.Rooms.Add(MakeShareable(new FGrpcGameRoomResponse(element)));
    }

    return GetDungeonDataResponse;
}

void UGrpcGameGetDungeonDataResponseHelperLibrary::BreakGetDungeonDataResponse(const FGrpcGameGetDungeonDataResponse& GetDungeonDataResponse,  
    TArray<FGrpcGameRoomResponse>& Rooms 
)
{
    for (auto& element : GetDungeonDataResponse.Rooms)
    {
        Rooms.Add(*(element.Get()));
    }
}

