//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SGame/GameMessage.h"
#include "TurboLinkGrpcContext.h"
#include "game.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::game::GetDungeonDataRequest* in, FGrpcGameGetDungeonDataRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGameGetDungeonDataRequest* in, ::game::GetDungeonDataRequest* out);

void GRPC_TO_TURBOLINK(const ::game::GetDungeonDataResponse* in, FGrpcGameGetDungeonDataResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGameGetDungeonDataResponse* in, ::game::GetDungeonDataResponse* out);

void GRPC_TO_TURBOLINK(const ::game::LoginRequest* in, FGrpcGameLoginRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGameLoginRequest* in, ::game::LoginRequest* out);

void GRPC_TO_TURBOLINK(const ::game::LoginResponse* in, FGrpcGameLoginResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGameLoginResponse* in, ::game::LoginResponse* out);

void GRPC_TO_TURBOLINK(const ::game::LogoutRequest* in, FGrpcGameLogoutRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGameLogoutRequest* in, ::game::LogoutRequest* out);

void GRPC_TO_TURBOLINK(const ::game::LogoutResponse* in, FGrpcGameLogoutResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGameLogoutResponse* in, ::game::LogoutResponse* out);

void GRPC_TO_TURBOLINK(const ::game::PlayerRequest* in, FGrpcGamePlayerRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGamePlayerRequest* in, ::game::PlayerRequest* out);

void GRPC_TO_TURBOLINK(const ::game::MoveRequest* in, FGrpcGameMoveRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGameMoveRequest* in, ::game::MoveRequest* out);

void GRPC_TO_TURBOLINK(const ::game::RoomResponse* in, FGrpcGameRoomResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGameRoomResponse* in, ::game::RoomResponse* out);

typedef grpc::ClientAsyncResponseReader<::game::LoginResponse> DungeonService_Login_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::game::LogoutResponse> DungeonService_Logout_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::game::RoomResponse> DungeonService_GetCurrentRoom_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::game::RoomResponse> DungeonService_Move_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::game::GetDungeonDataResponse> DungeonService_GetDungeonData_ReaderWriter;
