//Generated by TurboLink CodeGenerator, do not edit!
#include "GameService_Private.h"

void UDungeonServiceLoginLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGameLoginResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnLoginResponse.RemoveDynamic(this, &UDungeonServiceLoginLambdaWrapper::OnResponse);
}

void UDungeonServiceLogoutLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGameLogoutResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnLogoutResponse.RemoveDynamic(this, &UDungeonServiceLogoutLambdaWrapper::OnResponse);
}

void UDungeonServiceGetCurrentRoomLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGameRoomResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetCurrentRoomResponse.RemoveDynamic(this, &UDungeonServiceGetCurrentRoomLambdaWrapper::OnResponse);
}

void UDungeonServiceMoveLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGameRoomResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnMoveResponse.RemoveDynamic(this, &UDungeonServiceMoveLambdaWrapper::OnResponse);
}

void UDungeonServiceGetDungeonDataLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGameGetDungeonDataResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetDungeonDataResponse.RemoveDynamic(this, &UDungeonServiceGetDungeonDataLambdaWrapper::OnResponse);
}

