//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SGame/GameService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "game.grpc.pb.h"
#include "GameService_Private.generated.h"

class UDungeonService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::game::DungeonService::Stub> Stub;
};


UCLASS()
class UDungeonServiceLoginLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UDungeonServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameLoginResponse& Response);
public:
	FGrpcContextHandle Handle;
	UDungeonService::FLoginResponseLambda ResponseLambda;
};

UCLASS()
class UDungeonServiceLogoutLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UDungeonServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameLogoutResponse& Response);
public:
	FGrpcContextHandle Handle;
	UDungeonService::FLogoutResponseLambda ResponseLambda;
};

UCLASS()
class UDungeonServiceGetCurrentRoomLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UDungeonServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameRoomResponse& Response);
public:
	FGrpcContextHandle Handle;
	UDungeonService::FGetCurrentRoomResponseLambda ResponseLambda;
};

UCLASS()
class UDungeonServiceMoveLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UDungeonServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameRoomResponse& Response);
public:
	FGrpcContextHandle Handle;
	UDungeonService::FMoveResponseLambda ResponseLambda;
};

UCLASS()
class UDungeonServiceGetDungeonDataLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UDungeonServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameGetDungeonDataResponse& Response);
public:
	FGrpcContextHandle Handle;
	UDungeonService::FGetDungeonDataResponseLambda ResponseLambda;
};

